#
#Wed May 06 00:23:11 GMT-05:00 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, --no-sandbox, --disable-dev-shm-usage, --disable-gpu, --window-size\=1920,1080, remote-allow-origins\=*], extensions\=[]}
